version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "maven"
    directory: "/.dependabot/"
    schedule:
      interval: "daily"
      time: "19:50"
      # Disable all pull requests
    open-pull-requests-limit: 0
