version: 2
updates:
  # Configuration for Maven
  - package-ecosystem: "maven"
    directory: "/.dependabot/"
    schedule:
      interval: "daily"
      time: "20:35"
    # Disable all pull requests
    open-pull-requests-limit: 0
